---
Name: testsessionroutes
---
SilverStripe\Dev\DevelopmentAdmin:
  controllers:
    testsession:
      class: 'SilverStripe\TestSession\TestSessionController'
      description: 'Create a test session'
